In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
plt.rcParams['font.sans-serif']=['SimHei']
plt.rcParams['axes.unicode_minus'] = False

In [12]:
ped=pd.read_csv("F:\\Python\\pedigree.csv",sep=",",encoding='gbk',low_memory=False)

In [13]:
ped.head()

             牛号       出生日期  父国别        父号  母国别            母号
0  110001000001   2000/1/6  CHN  11193546  CHN  110001099169
1  110001000003  2000/1/10  CHN  31195515  CHN  110001095046
2  110001000006  2000/1/16  CHN  31195515  CHN  110001094056
3  110001000007  2000/1/21  CHN  11194143  CHN  110001096113
4  110001000008  2000/1/20  CHN  11194143  CHN  110001090136

In [14]:
ped1=ped[['牛号','出生日期','父号','母号']]

# 所有牛号重新编号

In [23]:
a=pd.DataFrame()
b=pd.DataFrame()
c=pd.DataFrame()

In [25]:
a['牛号']=ped1['牛号']
b['牛号']=ped1['母号']
c['牛号']=ped1['父号']

In [27]:
pedlist=pd.concat([a,b,c])

In [28]:
pedlist.count()

牛号    7283320
dtype: int64

In [46]:
pedlist1=pedlist.drop_duplicates(keep='first').dropna(how='any')

In [49]:
pedlist1.count()

牛号    4023122
dtype: int64

In [50]:
len(pedlist1)

4023122

In [54]:
pedlist1['CODE']=range(1,len(pedlist1)+1)

In [57]:
pedlist1.count()

牛号      4023122
CODE    4023122
dtype: int64

# 匹配原牛号

In [62]:
pedlist2=pedlist1[:].rename(columns={'牛号':'母号','CODE':'DAM'})
pedlist3=pedlist1[:].rename(columns={'牛号':'父号','CODE':'SIRE'})

In [59]:
ped1.count()

牛号      2860944
出生日期    2788162
父号      2251424
母号      2170952
dtype: int64

In [66]:
ped2=pd.merge(ped1,pedlist1,on='牛号',how='left')
ped3=pd.merge(ped2,pedlist2,on='母号',how='left')
ped4=pd.merge(ped3,pedlist3,on='父号',how='left')

In [68]:
ped4.count()

牛号      2860944
出生日期    2788162
父号      2251424
母号      2170952
CODE    2860944
DAM     2170952
SIRE    2251424
dtype: int64

In [69]:
ped4.to_csv("F:\\Python\\Pedigree.csv",sep=",",encoding='utf_8_sig',index=False)

In [70]:
ped4['valid']=ped4['CODE']==ped4['SIRE']

In [71]:
ped4.sort_values(by='valid')

,牛号,出生日期,父号,母号,CODE,DAM,SIRE,valid
0,110001000001,2000/1/6,11193546,110001099169,1,1827.0,3970806.0,False
1907290,34001615A541,2015/12/18,11109745,34001632000112A435,1907291,3652385.0,3971561.0,False
1907291,34001615A542,2015/12/19,HOUSAM135747713,34001632000110A244,1907292,3652386.0,3640267.0,False
1907292,34001615C006,2015/1/10,HOUSAM65283042,32000310g065,1907293,1822600.0,4007953.0,False
1907293,34001615C007,2015/1/11,15505190,32000311c227,1907294,1822724.0,3988176.0,False
1907294,34001615C009,2015/1/13,HOUSAM63470234,32000311c247,1907295,1822739.0,4008050.0,False
1907295,34001615C011,2015/1/14,15505190,32000312f138,1907296,1822939.0,3988176.0,False
1907296,34001615C012,2015/1/16,HOUSAM63470234,32000311c233,1907297,1822727.0,4008050.0,False
1907297,34001615C014,2015/1/20,HOUSAM64788382,32000308c241,1907298,1822261.0,4008051.0,False
1907298,34001615C015,2015/1/22,15505190,32000312f140,1907299,1822941.0,3988176.0,False
1907299,34001615C016,2015/1/23,HOUSAM63470234,32000308f022,1907300,1822295.0,4008050.0,False
1907300,34001615C017,2015/1/23,HOUSAM63470234,32000311c259,1907301,1822750.0,4008050.0,False
1907301,34001615C019,2015/1/24,HOUSAM63470234,32000311c288,1907302,1822772.0,4008050.0,False
1907302,34001615C020,2015/1/24,HOUSAM63470234,32000311z050,1907303,1822816.0,4008050.0,False
1907303,34001615C021,2015/1/25,HOUSAM63470234,32000311c218,1907304,1822718.0,4008050.0,False
1907304,34001615C022,2015/1/25,HOUSAM138821010,32000107a255,1907305,3652387.0,4007960.0,False
1907305,34001615C023,2015/1/2,HOUSAM63470234,32000311C254,1907306,3639404.0,4008050.0,False
1907306,34001615C025,2015/1/26,15505190,32000313f007,1907307,1823049.0,3988176.0,False
1907289,34001615A525,2015/11/28,11109745,34001632000113A391,1907290,3652384.0,3971561.0,False
1907288,34001615A523,2015/11/25,37310037,34001632000113A429,1907289,3652383.0,3975511.0,False
1907287,34001615A522,2015/11/24,37310037,34001632000113A403,1907288,3652382.0,3975511.0,False
1907286,34001615A520,2015/11/19,37310037,34001632000113A384,1907287,3652381.0,3975511.0,False
1907268,34001615A485,2015/11/29,HOUSAM65283042,34001632000112A231,1907269,3652363.0,4007953.0,False
1907269,34001615A486,2015/12/1,11109745,34001632000111A408,1907270,3652364.0,3971561.0,False
1907270,34001615A487,2015/12/1,HOUSAM65283042,34001632000113A241,1907271,3652365.0,4007953.0,False
1907271,34001615A488,2015/12/2,HOCANM9882453,34001632000109A217,1907272,3652366.0,4008500.0,False
1907272,34001615A492,2015/12/3,HOUSAM135747713,34001632000113A009,1907273,3652367.0,3640267.0,False
1907273,34001615A496,2015/12/4,11109745,34001632000113A281,1907274,3652368.0,3971561.0,False
1907274,34001615A497,2015/12/6,HOFRAM4435729424,34001632000110A358,1907275,3652369.0,4007963.0,False
1907275,34001615A498,2015/12/7,37308027,34001632000112A219,1907276,3652370.0,2990271.0,False
...,...,...,...,...,...,...,...,...
953668,151087120606,2012/6/3,7HO8744,10147,953669,3023013.0,3253669.0,False
953669,151087120607,2012/6/3,60384065,063892,953670,3255473.0,3987564.0,False
953670,151087120608,2012/6/3,60384065,063891,953671,3255474.0,3987564.0,False
953671,151087120609,2012/6/4,151049902544,7HO8744,953672,3253669.0,3987490.0,False
953672,151087120610,2012/6/4,151049003388,7HO8744,953673,3253669.0,3987489.0,False
953673,151087120611,2012/6/4,151049903839,7HO8744,953674,3253669.0,894667.0,False
953665,151087120603,2012/6/2,7HO8744,10073,953666,3022985.0,3253669.0,False
953633,151087120571,2012/5/27,777HO05584,83392,953634,3253661.0,3253530.0,False
953654,151087120592,2012/5/31,7HO8744,906909,953655,3253673.0,3253669.0,False
953652,151087120590,2012/5/31,7HO8744,903475,953653,3253674.0,3253669.0,False
953635,151087120573,2012/5/27,134314970,33696,953636,3165130.0,3987153.0,False
953636,151087120574,2012/5/27,614HO05359,83723,953637,3253660.0,3982592.0,False
953637,151087120575,2012/5/27,190749283,063888,953638,3255470.0,3987555.0,False
953638,151087120576,2012/5/27,17349617,34677,953639,3253659.0,3978287.0,False
953639,151087120577,2012/5/27,17349617,33106,953640,3253658.0,3978287.0,False
953640,151087120578,2012/5/28,7HO7452,A01934,953641,3253664.0,3987460.0,False
953641,151087120579,2012/5/28,777HO05139,83264,953642,3253663.0,3253777.0,False
953642,151087120580,2012/5/28,11103832,0101003,953643,3253662.0,3287215.0,False
953653,151087120591,2012/5/31,777HO05584,83313,953654,3255472.0,3253530.0,False
953643,151087120581,2012/5/29,007HO08744,901498,953644,3253667.0,3986514.0,False
953645,151087120583,2012/5/29,17349617,34679,953646,3253665.0,3978287.0,False
953646,151087120584,2012/5/30,11103832,063889,953647,3255471.0,3287215.0,False
953647,151087120585,2012/5/30,17349617,33109,953648,3253672.0,3978287.0,False
953648,151087120586,2012/5/30,151049101314,614HO4924,953649,3253671.0,3987487.0,False
953649,151087120587,2012/5/30,7HO8744,901623,953650,3253670.0,3253669.0,False
953650,151087120588,2012/5/30,151049900428,7HO8744,953651,3253669.0,3987486.0,False
953651,151087120589,2012/5/30,7HO8744,38103,953652,3130895.0,3253669.0,False
953644,151087120582,2012/5/29,777HO05584,83370,953645,3253666.0,3253530.0,False
2860943,M01110001927,2006/2/12,856032,NaN,2860944,NaN,4023122.0,False
2857740,65N118133045,2013/2/27,65N118133045,65N118133045,2857741,2857741.0,2857741.0,True